package mjv.spring.web.mvc.model;

public enum Escolaridade {
	ANALFABETO,LE_ESCREVE,FUNDAMENTAL_INCOMPLETO,
	ENSINO_FUNDAMENTAL,ENSINO_MEDIO_INCOMPLETO,ENSINO_MEDIO_COMPLETO,
	SUPERIOR,MESTRADO,DOUTORADO;
}
